<?php

/**
 * @file
 *
 * Add a field widget option for automatically tagging taxonomy term parents on
 * a per field basis.
 */

/**
 * Implements hook_field_form_field_ui_field_edit_form_alter().
 */
function term_parent_autotag_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if (in_array($form['#field']['type'], array('taxonomy_term_reference'))) {
    $form['instance']['term_parent_autotag'] = array(
      '#type' => 'checkbox',
      '#title' => t('Tag parents automatically'),
      '#weight' => -4,
      '#default_value' => isset($form['#instance']['term_parent_autotag']) ? $form['#instance']['term_parent_autotag'] : '',
    );
  }
}

/**
 * Implements hook_entity_presave().
 */
function term_parent_autotag_entity_presave($entity, $type) {
  // @TODO is type property always set
  $fields = field_info_instances($type, $entity->type);
  foreach ($fields as $field_name => $field_info) {
    if (!empty($field_info['term_parent_autotag'])) {
      term_parent_autotag_tag_parents($type, $entity, $field_name);
    }
  }
}

/**
 * Tag the parent terms automatically.
 */
function term_parent_autotag_tag_parents($entity_type, $entity, $field_name) {
  if ($term_field = field_get_items($entity_type, $entity, $field_name)) {

    // Generate an array of term ids. Required to check if a category
    // already is tagged.
    $term_index = array();
    foreach ($term_field as $term) {
      $term_index[] = $term['tid'];
    }

    foreach ($term_index as $term) {
      // Iterate over all term parents.
      $parents = taxonomy_get_parents($term);
      foreach ($parents as $parent) {
        // The parent is not tagged, force-tag it.
        if (!in_array($parent->tid, $term_index)) {
          $langcode = field_language($entity_type, $entity, $field_name);
          $entity->{$field_name}[$langcode][] = array('tid' => $parent->tid);
        }
      }
    }
  }
}
